// UI
export const SET_BANNER = 'SET_BANNER';


// DATA
export const INSTANCES_FETCH_REQUEST = 'INSTANCES_FETCH_REQUEST';
export const INSTANCES_FETCH_SUCCESS = 'INSTANCES_FETCH_SUCCESS';
export const INSTANCES_FETCH_FAILURE = 'INSTANCES_FETCH_FAILURE';

export const INSTANCE_CREATE_REQUEST = 'INSTANCE_CREATE_REQUEST';
export const INSTANCE_CREATE_SUCCESS = 'INSTANCE_CREATE_SUCCESS';
export const INSTANCE_CREATE_FAILURE = 'INSTANCE_CREATE_FAILURE';

export const INSTANCE_UPDATE_REQUEST = 'INSTANCE_UPDATE_REQUEST';
export const INSTANCE_UPDATE_SUCCESS = 'INSTANCE_UPDATE_SUCCESS';
export const INSTANCE_UPDATE_FAILURE = 'INSTANCE_UPDATE_FAILURE';

export const INSTANCE_DELETE_REQUEST = 'INSTANCE_DELETE_REQUEST';
export const INSTANCE_DELETE_SUCCESS = 'INSTANCE_DELETE_SUCCESS';
export const INSTANCE_DELETE_FAILURE = 'INSTANCE_DELETE_FAILURE';


// USER
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_PAYLOAD_REQUEST = 'USER_PAYLOAD_REQUEST';
export const USER_PAYLOAD_SUCCESS = 'USER_PAYLOAD_SUCCESS';
export const USER_PAYLOAD_FAILURE = 'USER_PAYLOAD_FAILURE';


// ---
// RPC
export const RPC_INSTANCE_CREATE = 'instance_create';
export const RPC_INSTANCE_UPDATE = 'instance_update';


// -------
// CHANGE FEED
export const FEED_INSTANCES_INSERT = 'feed_instances_insert';
export const FEED_INSTANCES_UPDATE = 'feed_instances_update';
export const FEED_INSTANCES_DELETE = 'feed_instances_delete';
