export const API = 'API';

// DATA

// USER
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_PAYLOAD_REQUEST = 'USER_PAYLOAD_REQUEST';
export const USER_PAYLOAD_SUCCESS = 'USER_PAYLOAD_SUCCESS';
export const USER_PAYLOAD_FAILURE = 'USER_PAYLOAD_FAILURE';


// ---
// RPC


// -------
// CHANGES
