export const API = 'API';

// DATA
export const INSTANCES_FETCH_REQUEST = 'INSTANCES_FETCH_REQUEST';
export const INSTANCES_FETCH_SUCCESS = 'INSTANCES_FETCH_SUCCESS';
export const INSTANCES_FETCH_FAILURE = 'INSTANCES_FETCH_FAILURE';

export const INSTANCES_UPDATE_REQUEST = 'INSTANCES_UPDATE_REQUEST';
export const INSTANCES_UPDATE_SUCCESS = 'INSTANCES_UPDATE_SUCCESS';
export const INSTANCES_UPDATE_FAILURE = 'INSTANCES_UPDATE_FAILURE';


// USER
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_PAYLOAD_REQUEST = 'USER_PAYLOAD_REQUEST';
export const USER_PAYLOAD_SUCCESS = 'USER_PAYLOAD_SUCCESS';
export const USER_PAYLOAD_FAILURE = 'USER_PAYLOAD_FAILURE';


// ---
// RPC


// -------
// CHANGES
